# Generated by Django 5.0.7 on 2024-08-03 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Police',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_no', models.CharField(max_length=8, unique=True)),
                ('status', models.CharField(choices=[('T', 'Teklif'), ('P', 'Poliçeleşmiş')], max_length=1)),
                ('brans_kodu', models.CharField(max_length=3)),
                ('prim', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tanzim_tarihi', models.DateTimeField(auto_now_add=True)),
                ('baslangic_tarihi', models.DateTimeField()),
                ('bitis_tarihi', models.DateTimeField()),
                ('musteri_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('onaylayan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onaylayan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OdemeBilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odeme_tutari', models.DecimalField(decimal_places=2, max_digits=10)),
                ('odeme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kredi_kart_no', models.CharField(max_length=16)),
                ('kredi_kart_sahibi', models.CharField(max_length=100)),
                ('son_kullanma_tarihi', models.CharField(max_length=5)),
                ('cvv', models.CharField(max_length=3)),
                ('police_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.police')),
            ],
        ),
        migrations.CreateModel(
            name='AracBilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaka_il_kodu', models.IntegerField()),
                ('plaka_kodu', models.CharField(max_length=10)),
                ('arac_marka', models.CharField(max_length=255)),
                ('arac_model', models.CharField(max_length=255)),
                ('arac_model_yili', models.IntegerField()),
                ('motor_no', models.CharField(max_length=50)),
                ('sasi_no', models.CharField(max_length=50)),
                ('police_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.police')),
            ],
        ),
    ]
