# Generated by Django 5.0.7 on 2024-08-04 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_police_odemebilgileri_aracbilgileri'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aracbilgileri',
            options={'verbose_name_plural': 'Poliçe Araç Bilgileri'},
        ),
        migrations.AlterModelOptions(
            name='odemebilgileri',
            options={'verbose_name_plural': 'Ödeme Bilgileri'},
        ),
        migrations.AlterModelOptions(
            name='police',
            options={'verbose_name_plural': 'Poliçeler'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name_plural': 'Araçlar'},
        ),
        migrations.AlterField(
            model_name='aracbilgileri',
            name='motor_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='aracbilgileri',
            name='sasi_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='PoliceTeklif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaka_il_kodu', models.IntegerField()),
                ('plaka_kodu', models.CharField(max_length=10)),
                ('arac_marka', models.CharField(max_length=255)),
                ('arac_model', models.CharField(max_length=255)),
                ('arac_model_yili', models.IntegerField()),
                ('kasko_degeri', models.DecimalField(decimal_places=2, max_digits=10)),
                ('teklif_fiyati', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Teklifler',
            },
        ),
    ]
