# Generated by Django 5.0.7 on 2024-08-04 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_aracbilgileri_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policeteklif',
            name='motor_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='policeteklif',
            name='police_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.police'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policeteklif',
            name='sasi_no',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
