# Generated by Django 5.0.7 on 2024-08-09 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_policeteklif_motor_no_policeteklif_police_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='police',
            name='police_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='SaglikBilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yatarak_tedavi', models.BooleanField(default=False)),
                ('ayakta_tedavi', models.BooleanField(default=False)),
                ('asistans_paketi', models.BooleanField(default=False)),
                ('doktor_danismanlik_hizmetleri', models.BooleanField(default=False)),
                ('police_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.police')),
            ],
        ),
    ]
