# Generated by Django 5.0.7 on 2024-08-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_police_police_no_saglikbilgileri'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saglikbilgileri',
            options={'verbose_name_plural': 'SaglikBilgileri'},
        ),
        migrations.AddField(
            model_name='policeteklif',
            name='asistans_paketi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policeteklif',
            name='ayakta_tedavi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policeteklif',
            name='brans_kodu',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policeteklif',
            name='doktor_danismanlik_hizmetleri',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policeteklif',
            name='yatarak_tedavi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='policeteklif',
            name='arac_marka',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policeteklif',
            name='arac_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policeteklif',
            name='arac_model_yili',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policeteklif',
            name='kasko_degeri',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='policeteklif',
            name='motor_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='policeteklif',
            name='plaka_il_kodu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policeteklif',
            name='plaka_kodu',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='policeteklif',
            name='sasi_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='policeteklif',
            name='teklif_fiyati',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
