# Generated by Django 5.0.7 on 2024-08-09 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_saglikbilgileri_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aracbilgileri',
            name='teklif_fiyati',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saglikbilgileri',
            name='teklif_fiyati',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saglikbilgileri',
            name='police_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.police'),
        ),
        migrations.DeleteModel(
            name='PoliceTeklif',
        ),
    ]
