# Generated by Django 5.0.7 on 2024-08-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_aracbilgileri_teklif_fiyati_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaglikPlanlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_adi', models.CharField(max_length=255)),
                ('yatarak_tedavi', models.BooleanField(default=False)),
                ('ayakta_tedavi', models.BooleanField(default=False)),
                ('asistans_paketi', models.BooleanField(default=False)),
                ('doktor_danismanlik_hizmetleri', models.BooleanField(default=False)),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
