# Generated by Django 5.0.7 on 2024-08-09 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_saglikplanlar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saglikbilgileri',
            options={'verbose_name_plural': 'Saglik Poliçesi Bilgileri'},
        ),
        migrations.AlterModelOptions(
            name='saglikplanlar',
            options={'verbose_name_plural': 'Saglik Planları'},
        ),
        migrations.CreateModel(
            name='DaskBilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bina_tipi', models.CharField(choices=[('betonarme', 'Betonarme'), ('celik', 'Çelik'), ('ahsap', 'Ahşap'), ('yigma', 'Yığma')], max_length=50)),
                ('bina_yasi', models.IntegerField()),
                ('kat_sayisi', models.IntegerField()),
                ('bina_alani', models.FloatField()),
                ('risk_bolgesi', models.CharField(choices=[('bolge_1', 'Bölge 1 (En yüksek risk)'), ('bolge_2', 'Bölge 2'), ('bolge_3', 'Bölge 3'), ('bolge_4', 'Bölge 4'), ('bolge_5', 'Bölge 5 (En düşük risk)')], max_length=50)),
                ('teklif_fiyati', models.DecimalField(decimal_places=2, max_digits=10)),
                ('police_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.police')),
            ],
        ),
    ]
