# Generated by Django 5.0.7 on 2024-07-27 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_myuser_groups_myuser_user_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='tc_kimlik_no',
            new_name='Id_No',
        ),
    ]
